### ISSUE TITLE
Error latest Paper version git-Paper-38

### ISSUE THREAD

**Issue by Lespleiades** [NathanCollaert/RewardsLite#24]
Hello! i have this error ounder latest vesrion of paper and LitePlaytimeRewards-2.4.7

`[LitePlaytimeRewards] Enabling LitePlaytimeRewards v2.4.7
[08:51:33 ERROR]: Error occurred while enabling LitePlaytimeRewards v2.4.7 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.get(String, Object)" because "section" is null
        at org.bukkit.configuration.MemorySection.get(MemorySection.java:265) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.get(MemorySection.java:230) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.contains(MemorySection.java:119) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.MemorySection.contains(MemorySection.java:114) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at com.tchristofferson.configupdater.KeyBuilder.parseLine(KeyBuilder.java:29) ~[LitePlaytimeRewards-2.4.7.jar:?]
        at com.tchristofferson.configupdater.ConfigUpdater.parseIgnoredSections(ConfigUpdater.java:156) ~[LitePlaytimeRewards-2.4.7.jar:?]
        at com.tchristofferson.configupdater.ConfigUpdater.update(ConfigUpdater.java:29) ~[LitePlaytimeRewards-2.4.7.jar:?]
        at com.backtobedrock.LitePlaytimeRewards.LitePlaytimeRewards.createFiles(LitePlaytimeRewards.java:130) ~[LitePlaytimeRewards-2.4.7.jar:?]
        at com.backtobedrock.LitePlaytimeRewards.LitePlaytimeRewards.initialize(LitePlaytimeRewards.java:77) ~[LitePlaytimeRewards-2.4.7.jar:?]
        at com.backtobedrock.LitePlaytimeRewards.LitePlaytimeRewards.onEnable(LitePlaytimeRewards.java:47) ~[LitePlaytimeRewards-2.4.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.18.jar:git-Paper-38]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.18.jar:git-Paper-38]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.jar:git-Paper-38]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.jar:git-Paper-38]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-38]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.jar:git-Paper-38]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-38]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:51:33 INFO]: [LitePlaytimeRewards] Disabling LitePlaytimeRewards v2.4.7`

**Comment by NathanCollaert** [comment]
Fixed in version 2.4.8.
