### ISSUE TITLE
1.20.4 error

### ISSUE THREAD

**Issue by PiweeX** [NathanCollaert/RewardsLite#64]
```diff
! [Sun 13:37:43 WARN ] 	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163)
! [Sun 13:37:43 WARN ] 	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161)
! [Sun 13:37:43 WARN ] 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120)
! [Sun 13:37:43 WARN ] 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
! [Sun 13:37:43 WARN ] 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
! [Sun 13:37:43 WARN ] 	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309)
! [Sun 13:37:43 WARN ] 	at Rewardslite-3.1.6.jar//com.backtobedrock.rewardslite.mappers.player.YAMLPlayerMapper.getConfig(YAMLPlayerMapper.java:250)
! [Sun 13:37:43 WARN ] 	at Rewardslite-3.1.6.jar//com.backtobedrock.rewardslite.mappers.player.YAMLPlayerMapper.upsertPlayerData(YAMLPlayerMapper.java:200)
! [Sun 13:37:43 WARN ] 	at Rewardslite-3.1.6.jar//com.backtobedrock.rewardslite.mappers.player.YAMLPlayerMapper.lambda$updatePlayerData$17(YAMLPlayerMapper.java:191)
! [Sun 13:37:43 WARN ] 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
! [Sun 13:37:43 WARN ] 	... 6 more
! [Sun 13:37:43 WARN ] Caused by: java.lang.IllegalArgumentException: Specified class does not exist ('Reward')
! [Sun 13:37:43 WARN ] 	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:199)
! [Sun 13:37:43 WARN ] 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58)
! [Sun 13:37:43 WARN ] 	... 19 more
  [Sun 13:37:43 INFO  Server/PlayerConnection] Ph1nt0m issued server command: /playtime
! [Sun 13:37:50 WARN ] java.util.concurrent.CompletionException: org.yaml.snakeyaml.error.YAMLException: Could not deserialize object```

**Comment by NathanCollaert** [comment]
Should be fixed in version 3.1.7.
