### ISSUE TITLE
playtime rewards not triggering, error on /playtime

### ISSUE THREAD

**Issue by rbos** [NathanCollaert/RewardsLite#70]
when players type '/playtime' RewardsLite generates an error. Also, it's not triggering when players hit their threshold.

```
[14:50:25 INFO]: ___ghast issued server command: /playtime
[14:50:25 ERROR]: Command exception: /playtime
org.bukkit.command.CommandException: Unhandled exception executing command 'playtime' in plugin RewardsLite v3.1.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1627) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at RewardsLite.jar/com.backtobedrock.rewardslite.domain.enumerations.MinecraftVersion.get(MinecraftVersion.java:37) ~[RewardsLite.jar:?]
        at RewardsLite.jar/com.backtobedrock.rewardslite.commands.CommandPlaytime.execute(CommandPlaytime.java:20) ~[RewardsLite.jar:?]
        at RewardsLite.jar/com.backtobedrock.rewardslite.commands.Commands.onCommand(Commands.java:38) ~[RewardsLite.jar:?]
        at RewardsLite.jar/com.backtobedrock.rewardslite.Rewardslite.onCommand(Rewardslite.java:69) ~[RewardsLite.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 26 more

```

and `playtime [player]` from console fails with:

```
> playtime rbos
[14:52:22 WARN]: Unexpected exception while parsing console command "playtime rbos"
org.bukkit.command.CommandException: Unhandled exception executing command 'playtime' in plugin RewardsLite v3.1.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:985) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-110-6d7a438]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at RewardsLite.jar/com.backtobedrock.rewardslite.domain.enumerations.MinecraftVersion.get(MinecraftVersion.java:37) ~[RewardsLite.jar:?]
        at RewardsLite.jar/com.backtobedrock.rewardslite.commands.CommandPlaytime.execute(CommandPlaytime.java:20) ~[RewardsLite.jar:?]
        at RewardsLite.jar/com.backtobedrock.rewardslite.commands.Commands.onCommand(Commands.java:38) ~[RewardsLite.jar:?]
        at RewardsLite.jar/com.backtobedrock.rewardslite.Rewardslite.onCommand(Rewardslite.java:69) ~[RewardsLite.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

**Comment by rbos** [comment]
Running Paper version 1.21.1-110-master@6d7a438, the latest RewardsLite as of the time of writing.

If it's relevant we have ~9000 playerdata files, but they seem to be valid YAML so no obvious corruption.
